services:
  flagd-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${FLAGD_UI_IMAGE:-flagd-ui:local}
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - '3000:3000'
    volumes:
      - ./flags:/app/flags

  flagd:
    image: ghcr.io/open-feature/flagd:latest
    volumes:
      - ./flags:/flags
    command: ['start', '--uri', 'file:./flags/demo.flagd.json']
    ports:
      - '8013:8013'
      - '8016:8016'
      - '8014:8014'

