/* This file is generated by scripts/generate-environments.js. */

export const GIT_TAG: string | null = null;
export const GIT_COMMIT_HASH: string | null = '5c7cea5414ca606c1c7a2526ea9b9bbadfc33bc1';
export const DEFAULT_BACKEND_ROOT: string | null = null;
